import os
os.system("docker version")
os.system("systemctl start docker")
os.system("docker pull ubuntu:14.04")
os.system("docker pull centos:latest")
os.system("docker images")
os.system("docker run -it --name webos:v1 centos:latest")
os.system("yum install httpd -y")
os.system("systemctl start httpd")
os.system("cd /var/www/html/")
os.system("cat > index.html Hello this is Rahul Banik conducting test on Docker")
os.system("/usr/sbin/httpd")
os.system("yum install net-tools")
os.system("netstat -tnlp | grep")
os.system("yum install python3")
os.system("python3")