print("Automating LVM partition USing python Script")
import os
os.system("fdisk -l")
os.system("yum install lvm2 -y")
os.system("pvcreate /dev/xvdf")
os.system("pvdisplay")
os.system("vgcreate Rahul /dev/xvdf")
os.system("vgdisplay")
os.system("lvcreate --size 5G --name LVM1 Rahul")
os.system("lvdisplay")
os.system("mkfs.ext4 /dev/Rahul/LVM1 /dn")
os.system("mount /dev/Rahul/LVM1 dn")
os.system("df -ht")
os.system("Complete...")
